language: go

sudo: false

os:
  - linux
  - osx

go:
  - 1.5

before_script:
  - sudo redis-server /etc/redis/redis.conf --port 6381

env:
  - REDIS_URL=tcp://127.0.0.1:6381/11

install:
  - go get -t ./...
  - go get -u github.com/golang/lint/golint
  - go get -u golang.org/x/tools/cmd/goimports
  - go get -u github.com/nats-io/gnatsd/...
  - go get -u github.com/nsqio/nsq/...

script:
  - gnatsd -DV &
  - go vet ./...
  - diff <(goimports -d .) <(printf "")
  - diff <(golint ./...) <(printf "")
  - go test -v -cpu=2 ./...
  - go test -v -cpu=1,2,4 -short -race ./...
